# Generated by Django 3.2.2 on 2021-06-08 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_article_view_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='article',
            name='publish_status',
            field=models.BooleanField(choices=[(False, '未发布'), (True, '发布')], default=False, verbose_name='发布状态'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_msg', models.CharField(max_length=255, verbose_name='回复内容')),
                ('reply_time', models.DateTimeField(auto_now_add=True, verbose_name='回复日期')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.comment')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '评论回复表',
            },
        ),
    ]
