# Generated by Django 3.2.2 on 2021-06-11 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20210608_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app01.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, through='app01.ArticleToTag', to='app01.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(max_length=32, null=True, verbose_name='站点名称'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_theme',
            field=models.CharField(max_length=32, null=True, verbose_name='站点样式'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_title',
            field=models.CharField(max_length=32, null=True, verbose_name='站点标题'),
        ),
    ]
