# Generated by Django 3.2.2 on 2021-06-20 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20210620_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verse',
            old_name='vsrse',
            new_name='name',
        ),
        migrations.AddField(
            model_name='verse',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.site'),
        ),
    ]
